import { describe, expect, it } from "vitest";
import { allocationBlockReason, auditLogsInRange, auditLogsSearch, getQuickDateRange, getReportStats, monthlyAllocationCount, parseCardCodes } from "../lib/cards/utils";
import { makeBackupEnvelope, validateBackupPayload } from "../lib/cards/backup-validation";
import { renderCardMessage } from "../lib/cards/message-template";

describe("بطاقات المخزون", () => {
  it("يستخرج الرموز الرقمية الفريدة فقط من اللصق متعدد الأسطر", () => { expect(parseCardCodes("123\nabc\n123\n\n4567\n12-34")).toEqual({ codes: ["123", "4567"], invalidCount: 2, duplicateCount: 1 }); });
  it("يحسب تخصيصات الشهر الحالي دون احتساب الأشهر السابقة", () => { const now = new Date(); const old = new Date(now.getFullYear(), now.getMonth() - 1, 1).toISOString(); const current = new Date(now.getFullYear(), now.getMonth(), 2).toISOString(); expect(monthlyAllocationCount([{ id: "a", code: "1", packageId: "p", subscriberId: "s", isFrozen: true, sentAt: current }, { id: "b", code: "2", packageId: "p", subscriberId: "s", isFrozen: true, sentAt: old }], "s", now)).toBe(1); });
  it("يمنع تخصيص بطاقة مجمدة أو تجاوز الحد الشهري", () => { const now = new Date(); const frozen = { id: "f", code: "1", packageId: "p", subscriberId: "s", isFrozen: true, sentAt: now.toISOString() }; expect(allocationBlockReason(frozen, [frozen], "other", now)).toContain("مجمدة"); const cards = [1, 2, 3].map((number) => ({ id: `${number}`, code: `${number}`, packageId: "p", subscriberId: "s", isFrozen: true, sentAt: now.toISOString() })); const fresh = { id: "x", code: "4", packageId: "p", subscriberId: null, isFrozen: false, sentAt: null }; expect(allocationBlockReason(fresh, cards, "s", now)).toContain("الحد الشهري"); });
  it("يحسب الإيراد من البطاقات المخصصة فقط", () => { const stats = getReportStats([], [{ id: "p", name: "10GB", price: 5, sizeGb: 10, createdAt: "" }], [{ id: "a", code: "1", packageId: "p", subscriberId: "s", isFrozen: true, sentAt: new Date().toISOString() }, { id: "b", code: "2", packageId: "p", subscriberId: null, isFrozen: false, sentAt: null }]); expect(stats.totalRevenue).toBe(5); expect(stats.availableCards).toBe(1); });
  it("يفلتر سجل التدقيق بين تاريخين شاملين", () => { const sample = (createdAt: string) => ({ id: createdAt, action: "allocation" as const, createdAt, cardId: "c", packageId: "p", subscriberId: "s", codeSnapshot: "1", subscriberName: "أحمد", subscriberPhone: "111", subscriberLocation: "الرياض", subscriberNotes: "", packageName: "10GB", packageSizeGb: 10, packagePrice: 5 }); const logs = [sample("2026-08-01T08:00:00.000Z"), sample("2026-08-15T08:00:00.000Z"), sample("2026-09-01T08:00:00.000Z")]; expect(auditLogsInRange(logs, { from: "2026-08-10", to: "2026-08-31" })).toHaveLength(1); });
  it("يبحث في سجل التدقيق بالاسم أو رمز البطاقة ويتجاهل الفراغ", () => { const logs = [{ id: "1", action: "allocation" as const, createdAt: "2026-08-15T08:00:00.000Z", cardId: "c1", packageId: "p", subscriberId: "s", codeSnapshot: "987654", subscriberName: "أحمد علي", subscriberPhone: "111", subscriberLocation: "الرياض", subscriberNotes: "", packageName: "10GB", packageSizeGb: 10, packagePrice: 5 }, { id: "2", action: "allocation" as const, createdAt: "2026-08-15T08:00:00.000Z", cardId: "c2", packageId: "p", subscriberId: "s2", codeSnapshot: "123456", subscriberName: "سارة", subscriberPhone: "222", subscriberLocation: "جدة", subscriberNotes: "", packageName: "20GB", packageSizeGb: 20, packagePrice: 10 }]; expect(auditLogsSearch(logs, "أحمد")).toHaveLength(1); expect(auditLogsSearch(logs, "123456")).toHaveLength(1); expect(auditLogsSearch(logs, "  ")).toHaveLength(2); });
  it("ينشئ نسخة احتياطية قابلة للاستعادة بعد المرور عبر JSON", () => { const data = { subscribers: [], packages: [], cards: [], auditLogs: [], settings: { profileImageUri: null, cardMessageTemplate: "مرحباً! كرتك: {card}", reportTitle: "عنوان مخصص", sendSections: { package: true, card: false, recipient: true, message: false } } }; const restored = validateBackupPayload(JSON.parse(JSON.stringify(makeBackupEnvelope(data)))); expect(restored.ok).toBe(true); if (restored.ok) expect(restored.data).toEqual(data); });
  it("يرفض النسخة الناقصة أو التي تحتوي رموزًا مكررة", () => { const base = { app: "بطاقات المشتركين", version: 1, createdAt: new Date().toISOString(), data: { subscribers: [], packages: [{ id: "p", name: "10GB", price: 5, sizeGb: 10, createdAt: "" }], cards: [{ id: "c1", code: "123", packageId: "p", subscriberId: null, isFrozen: false, sentAt: null }, { id: "c2", code: "123", packageId: "p", subscriberId: null, isFrozen: false, sentAt: null }], auditLogs: [] } }; expect(validateBackupPayload(base).ok).toBe(false); expect(validateBackupPayload({ ...base, data: { ...base.data, auditLogs: undefined } }).ok).toBe(false); });
  it("يستبدل متغيرات قالب الرسالة بالقيم المحفوظة", () => { expect(renderCardMessage("مرحباً! كرتك: {card} | فئة: {category} | شبكة: {network} - {wallet}", { card: "123456", category: "10GB", network: "زين", wallet: "محفظة 1" })).toBe("مرحباً! كرتك: 123456 | فئة: 10GB | شبكة: زين - محفظة 1"); });
  it("ينشئ فترات اليوم وآخر 7 أيام والشهر السابق بصيغة YYYY/MM/DD", () => { const reference = new Date(2026, 7, 31, 12, 0, 0); expect(getQuickDateRange("today", reference)).toEqual({ from: "2026/08/31", to: "2026/08/31" }); expect(getQuickDateRange("last7", reference)).toEqual({ from: "2026/08/25", to: "2026/08/31" }); expect(getQuickDateRange("previousMonth", reference)).toEqual({ from: "2026/07/01", to: "2026/07/31" }); });
  it("يقبل فلترة السجل بصيغة التاريخ ذات الشرطات المائلة", () => { const log = { id: "1", action: "allocation" as const, createdAt: "2026-08-31T12:00:00.000Z", cardId: "c", packageId: "p", subscriberId: "s", codeSnapshot: "123", subscriberName: "أحمد", subscriberPhone: "111", subscriberLocation: "الرياض", subscriberNotes: "", packageName: "10GB", packageSizeGb: 10, packagePrice: 5 }; expect(auditLogsInRange([log], { from: "2026/08/31", to: "2026/08/31" })).toHaveLength(1); });
});
