import { Asset } from "expo-asset";
import * as FileSystem from "expo-file-system/legacy";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { formatCurrency, formatDate } from "./utils";
import type { Card, Package, ReportStats, Subscriber } from "./types";

function escapeHtml(value: string) { return value.replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[char] ?? char); }
async function getArabicFontBase64() { const asset = Asset.fromModule(require("@/assets/fonts/NotoSansArabic.ttf")); await asset.downloadAsync(); if (!asset.localUri) throw new Error("تعذر تحميل الخط العربي."); return FileSystem.readAsStringAsync(asset.localUri, { encoding: FileSystem.EncodingType.Base64 }); }

export async function exportArabicReport({ subscribers, packages, cards, stats }: { subscribers: Subscriber[]; packages: Package[]; cards: Card[]; stats: ReportStats }) {
  const fontBase64 = await getArabicFontBase64();
  const packageMap = new Map(packages.map((item) => [item.id, item]));
  const allocatedRows = cards.filter((card) => card.subscriberId).map((card) => { const subscriber = subscribers.find((item) => item.id === card.subscriberId); return `<tr><td>${escapeHtml(subscriber?.name ?? "غير معروف")}</td><td dir="ltr">${escapeHtml(card.code)}</td><td>${escapeHtml(packageMap.get(card.packageId)?.name ?? "—")}</td><td>${formatDate(card.sentAt)}</td></tr>`; }).join("") || "<tr><td colspan=\"4\">لا توجد بطاقات مخصصة حتى الآن.</td></tr>";
  const html = `<!DOCTYPE html><html dir="rtl" lang="ar"><head><meta charset="utf-8" /><style>@font-face{font-family:NotoArabic;src:url(data:font/ttf;base64,${fontBase64}) format('truetype');}@page{margin:26px;}*{box-sizing:border-box;}body{font-family:NotoArabic,Arial,sans-serif;color:#16202A;direction:rtl;text-align:right;font-size:12px;}h1{font-size:24px;color:#0E2A47;margin:0 0 6px;}.sub{color:#51606F;margin-bottom:20px;}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin:0 0 20px;}.metric{border:1px solid #D8E2E8;border-right:4px solid #087E8B;border-radius:10px;padding:12px;background:#FAFCFD;}.metric span{display:block;color:#637381;font-size:10px;}.metric strong{font-size:18px;color:#0E2A47;}table{width:100%;border-collapse:collapse;margin-top:10px;}th{background:#0E2A47;color:#fff;padding:9px;text-align:right;}td{border-bottom:1px solid #DFE7EC;padding:8px;}.note{margin-top:18px;padding:10px;background:#F6F1E9;border-radius:8px;color:#48545D;}</style></head><body><h1>التقرير التشغيلي للبطاقات</h1><div class="sub">تاريخ الإنشاء: ${formatDate(new Date().toISOString())}</div><section class="grid"><div class="metric"><span>إجمالي المشتركين</span><strong>${stats.totalSubscribers}</strong></div><div class="metric"><span>إجمالي الباقات</span><strong>${stats.totalPackages}</strong></div><div class="metric"><span>إجمالي البطاقات</span><strong>${stats.totalCards}</strong></div><div class="metric"><span>البطاقات المخصصة</span><strong>${stats.allocatedCards}</strong></div><div class="metric"><span>الإيراد من البطاقات المخصصة</span><strong>${formatCurrency(stats.totalRevenue)}</strong></div><div class="metric"><span>متوسط سعر الباقة</span><strong>${formatCurrency(stats.averagePackagePrice)}</strong></div></section><h2>ملخص الشهر الحالي</h2><div class="note">تم تخصيص ${stats.monthlyAllocated} بطاقة هذا الشهر، ويتوفر ${stats.availableCards} بطاقة غير مخصصة في المخزون.</div><h2>سجل البطاقات المخصصة</h2><table><thead><tr><th>المشترك</th><th>الرمز</th><th>الباقة</th><th>تاريخ الإرسال</th></tr></thead><tbody>${allocatedRows}</tbody></table></body></html>`;
  const { uri } = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(uri, { mimeType: "application/pdf", dialogTitle: "مشاركة التقرير التشغيلي" });
  return uri;
}
