import { Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { LoadingState } from "@/components/cards/loading-state";
import { ScreenHeader } from "@/components/cards/screen-header";
import { ScreenContainer } from "@/components/screen-container";
import { exportAuditCsv } from "@/lib/cards/export-audit";
import { useCards } from "@/lib/cards/store";
import { auditLogsInRange, auditLogsSearch, dateRangeLabel, formatCurrency, formatDate } from "@/lib/cards/utils";
import { useState } from "react";

export default function AuditScreen() {
  const { auditLogs, isReady } = useCards();
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");
  const [query, setQuery] = useState("");
  if (!isReady) return <LoadingState />;
  const range = { from, to };
  const visibleLogs = auditLogsSearch(auditLogsInRange(auditLogs, range), query);
  const exportLog = async () => { try { await exportAuditCsv(visibleLogs, range); } catch { Alert.alert("تعذر التصدير", "تعذر إنشاء ملف سجل التدقيق. حاول مجددًا."); } };

  return <ScreenContainer className="px-4" containerClassName="bg-background"><FlatList data={visibleLogs} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<><ScreenHeader title="سجل التدقيق" subtitle="توثيق ثابت لكل تخصيص بطاقة" /><View style={styles.filter}><Text style={styles.filterTitle}>فلترة السجل</Text><TextInput value={query} onChangeText={setQuery} placeholder="ابحث باسم المشترك أو رمز البطاقة" placeholderTextColor="#9AA6AF" textAlign="right" style={styles.searchInput} /><View style={styles.inputRow}><TextInput value={to} onChangeText={setTo} placeholder="إلى YYYY-MM-DD" placeholderTextColor="#9AA6AF" textAlign="center" style={styles.input} /><TextInput value={from} onChangeText={setFrom} placeholder="من YYYY-MM-DD" placeholderTextColor="#9AA6AF" textAlign="center" style={styles.input} /></View><View style={styles.actions}><Pressable onPress={() => { setFrom(""); setTo(""); setQuery(""); }} style={styles.clear}><Text style={styles.clearText}>مسح الفلتر</Text></Pressable><Pressable onPress={exportLog} style={styles.export}><Text style={styles.exportText}>تصدير CSV</Text></Pressable></View><Text style={styles.filterHint}>{visibleLogs.length} عملية — {dateRangeLabel(range)}</Text></View></>} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyText}>لا توجد عمليات تخصيص ضمن هذه الفترة.</Text></View>} renderItem={({ item }) => <View style={styles.logCard}><View style={styles.logHeader}><Text style={styles.date}>{formatDate(item.createdAt)}</Text><Text style={styles.action}>تخصيص بطاقة</Text></View><Text style={styles.name}>{item.subscriberName}</Text><Text style={styles.meta}>{item.subscriberPhone} • {item.subscriberLocation || "بدون موقع"}</Text><View style={styles.infoRow}><Text style={styles.code}>{item.codeSnapshot}</Text><Text style={styles.package}>{item.packageName} • {item.packageSizeGb}GB • {formatCurrency(item.packagePrice)}</Text></View>{item.subscriberNotes ? <Text style={styles.notes}>ملاحظات: {item.subscriberNotes}</Text> : null}</View>} /></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { paddingTop: 20, paddingBottom: 32 }, filter: { backgroundColor: "#FFFFFF", borderRadius: 16, borderWidth: 1, borderColor: "#D8E2E8", padding: 14, marginBottom: 14 }, filterTitle: { textAlign: "right", color: "#16202A", fontWeight: "800", marginBottom: 10 }, searchInput: { minHeight: 44, backgroundColor: "#F6F1E9", color: "#16202A", borderRadius: 10, paddingHorizontal: 12, fontSize: 12, marginBottom: 8 }, inputRow: { flexDirection: "row-reverse", gap: 8 }, input: { flex: 1, minHeight: 44, backgroundColor: "#F6F1E9", color: "#16202A", borderRadius: 10, paddingHorizontal: 8, fontSize: 12 }, actions: { flexDirection: "row-reverse", gap: 8, marginTop: 10 }, export: { flex: 1, backgroundColor: "#0E2A47", borderRadius: 10, padding: 12, alignItems: "center" }, exportText: { color: "#FFFFFF", fontWeight: "800" }, clear: { flex: 1, backgroundColor: "#EAF5F4", borderRadius: 10, padding: 12, alignItems: "center" }, clearText: { color: "#087E8B", fontWeight: "800" }, filterHint: { marginTop: 10, color: "#637381", textAlign: "right", fontSize: 12 }, empty: { backgroundColor: "#FFFFFF", borderRadius: 16, padding: 20 }, emptyText: { color: "#637381", textAlign: "right" }, logCard: { backgroundColor: "#FFFFFF", borderRadius: 16, padding: 14, borderWidth: 1, borderColor: "#D8E2E8", marginBottom: 9 }, logHeader: { flexDirection: "row-reverse", justifyContent: "space-between" }, action: { color: "#087E8B", backgroundColor: "#EAF5F4", borderRadius: 999, paddingHorizontal: 8, paddingVertical: 4, fontSize: 11, fontWeight: "700" }, date: { color: "#637381", fontSize: 11 }, name: { color: "#16202A", fontSize: 16, fontWeight: "800", textAlign: "right", marginTop: 12 }, meta: { color: "#637381", textAlign: "right", marginTop: 3, fontSize: 12 }, infoRow: { flexDirection: "row-reverse", justifyContent: "space-between", borderTopWidth: 1, borderTopColor: "#EEF2F4", marginTop: 11, paddingTop: 10 }, code: { color: "#0E2A47", fontFamily: "monospace", fontWeight: "800" }, package: { color: "#637381", fontSize: 11 }, notes: { color: "#637381", backgroundColor: "#F6F1E9", borderRadius: 8, padding: 8, textAlign: "right", marginTop: 10, fontSize: 11 } });
