import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useState } from "react";

import { MetricCard } from "@/components/cards/metric-card";
import { LoadingState } from "@/components/cards/loading-state";
import { ScreenHeader } from "@/components/cards/screen-header";
import { ScreenContainer } from "@/components/screen-container";
import { exportArabicReport } from "@/lib/cards/report";
import { useCards } from "@/lib/cards/store";
import { auditLogsInRange, dateRangeLabel, formatCurrency } from "@/lib/cards/utils";

export default function ReportsScreen() {
  const { auditLogs, stats, isReady } = useCards();
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");
  if (!isReady) return <LoadingState />;
  const range = { from, to };
  const selectedLogs = auditLogsInRange(auditLogs, range);
  const selectedRevenue = selectedLogs.reduce((sum, log) => sum + log.packagePrice, 0);
  const exportReport = async () => { try { await exportArabicReport({ stats, auditLogs: selectedLogs, range }); } catch { Alert.alert("تعذر التصدير", "لم يتم إنشاء التقرير. تحقق من إذن مشاركة الملفات ثم حاول مجددًا."); } };

  return <ScreenContainer className="px-4" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><ScreenHeader title="التقارير" subtitle="اختر الفترة المطلوبة ثم صدر تقريراً يشمل بيانات المشتركين" /><View style={styles.filter}><Text style={styles.filterTitle}>فترة التقرير</Text><View style={styles.inputRow}><TextInput value={to} onChangeText={setTo} placeholder="إلى YYYY-MM-DD" placeholderTextColor="#9AA6AF" textAlign="center" style={styles.input} /><TextInput value={from} onChangeText={setFrom} placeholder="من YYYY-MM-DD" placeholderTextColor="#9AA6AF" textAlign="center" style={styles.input} /></View><View style={styles.filterActions}><Pressable onPress={() => { setFrom(""); setTo(""); }} style={styles.clear}><Text style={styles.clearText}>مسح الفترة</Text></Pressable><Text style={styles.rangeLabel}>{dateRangeLabel(range)}</Text></View></View><View style={styles.metrics}><MetricCard label="المشتركون" value={stats.totalSubscribers} tone="navy" /><MetricCard label="الباقات" value={stats.totalPackages} /></View><View style={styles.metrics}><MetricCard label="تخصيصات الفترة" value={selectedLogs.length} tone="sand" /><MetricCard label="إيراد الفترة" value={formatCurrency(selectedRevenue)} tone="gold" /></View><View style={styles.panel}><Text style={styles.panelTitle}>ملخص التقرير المحدد</Text><View style={styles.line}><Text style={styles.value}>{stats.availableCards}</Text><Text style={styles.label}>بطاقة متاحة حاليًا في المخزون</Text></View><View style={styles.line}><Text style={styles.value}>{selectedLogs.length}</Text><Text style={styles.label}>سجل تخصيص سيظهر في تقرير الفترة</Text></View><View style={styles.line}><Text style={styles.value}>{formatCurrency(stats.averagePackagePrice)}</Text><Text style={styles.label}>متوسط سعر الباقة الحالي</Text></View></View><View style={styles.reportCard}><Text style={styles.reportTitle}>تقرير عربي مفصل PDF</Text><Text style={styles.reportText}>يشمل الفترة المحددة وسجل التخصيص واسم المشترك وهاتفه وموقعه وملاحظاته، كما حُفظت وقت العملية.</Text><Pressable onPress={exportReport} style={({ pressed }) => [styles.export, pressed && styles.pressed]}><Text style={styles.exportText}>تصدير ومشاركة التقرير</Text></Pressable></View></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingTop: 20, paddingBottom: 32 }, filter: { backgroundColor: "#FFFFFF", borderRadius: 16, padding: 14, borderWidth: 1, borderColor: "#D8E2E8", marginBottom: 12 }, filterTitle: { color: "#16202A", textAlign: "right", fontWeight: "800", marginBottom: 10 }, inputRow: { flexDirection: "row-reverse", gap: 8 }, input: { flex: 1, minHeight: 44, borderRadius: 10, backgroundColor: "#F6F1E9", color: "#16202A", paddingHorizontal: 8, fontSize: 12 }, filterActions: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center", marginTop: 10 }, clear: { backgroundColor: "#EAF5F4", paddingHorizontal: 10, paddingVertical: 8, borderRadius: 8 }, clearText: { color: "#087E8B", fontWeight: "700", fontSize: 12 }, rangeLabel: { color: "#637381", fontSize: 11 }, metrics: { flexDirection: "row", gap: 10, marginBottom: 10 }, panel: { backgroundColor: "#FFFFFF", borderRadius: 18, padding: 16, borderWidth: 1, borderColor: "#D8E2E8", marginTop: 12 }, panelTitle: { color: "#16202A", fontSize: 17, fontWeight: "800", textAlign: "right", marginBottom: 8 }, line: { flexDirection: "row-reverse", justifyContent: "space-between", paddingVertical: 11, borderBottomWidth: 1, borderBottomColor: "#EEF2F4" }, label: { color: "#637381", textAlign: "right" }, value: { color: "#0E2A47", fontWeight: "800" }, reportCard: { marginTop: 16, backgroundColor: "#0E2A47", borderRadius: 18, padding: 18, alignItems: "flex-end" }, reportTitle: { color: "#FFFFFF", fontSize: 18, fontWeight: "800", textAlign: "right" }, reportText: { color: "#D3E5E8", textAlign: "right", lineHeight: 21, marginTop: 8 }, export: { marginTop: 16, backgroundColor: "#FFFFFF", paddingVertical: 13, paddingHorizontal: 18, borderRadius: 12, alignSelf: "stretch", alignItems: "center" }, exportText: { color: "#0E2A47", fontWeight: "800" }, pressed: { opacity: 0.72, transform: [{ scale: 0.98 }] } });
