import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { MetricCard } from "@/components/cards/metric-card";
import { LoadingState } from "@/components/cards/loading-state";
import { ScreenHeader } from "@/components/cards/screen-header";
import { ScreenContainer } from "@/components/screen-container";
import { exportArabicReport } from "@/lib/cards/report";
import { useCards } from "@/lib/cards/store";
import { formatCurrency } from "@/lib/cards/utils";

export default function ReportsScreen() { const { subscribers, packages, cards, stats, isReady } = useCards(); if (!isReady) return <LoadingState />; const exportReport = async () => { try { await exportArabicReport({ subscribers, packages, cards, stats }); } catch { Alert.alert("تعذر التصدير", "لم يتم إنشاء التقرير. تحقق من إذن مشاركة الملفات ثم حاول مجددًا."); } }; return <ScreenContainer className="px-4" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><ScreenHeader title="التقارير" subtitle="ملخص فوري للتشغيل والمخزون" /><View style={styles.metrics}><MetricCard label="المشتركون" value={stats.totalSubscribers} tone="navy" /><MetricCard label="الباقات" value={stats.totalPackages} /></View><View style={styles.metrics}><MetricCard label="إجمالي البطاقات" value={stats.totalCards} tone="sand" /><MetricCard label="البطاقات المخصصة" value={stats.allocatedCards} tone="gold" /></View><View style={styles.panel}><Text style={styles.panelTitle}>ملخص الشهر الحالي</Text><View style={styles.line}><Text style={styles.value}>{stats.monthlyAllocated}</Text><Text style={styles.label}>بطاقة تم تخصيصها هذا الشهر</Text></View><View style={styles.line}><Text style={styles.value}>{stats.availableCards}</Text><Text style={styles.label}>بطاقة متاحة في المخزون</Text></View><View style={styles.line}><Text style={styles.value}>{formatCurrency(stats.totalRevenue)}</Text><Text style={styles.label}>إيراد البطاقات المخصصة</Text></View><View style={styles.line}><Text style={styles.value}>{formatCurrency(stats.averagePackagePrice)}</Text><Text style={styles.label}>متوسط سعر الباقة</Text></View></View><View style={styles.reportCard}><Text style={styles.reportTitle}>تقرير عربي PDF</Text><Text style={styles.reportText}>ينشئ ملفاً عربي الاتجاه يضم المؤشرات وسجل البطاقات المخصصة، مع تضمين خط عربي داخل التقرير.</Text><Pressable onPress={exportReport} style={({ pressed }) => [styles.export, pressed && styles.pressed]}><Text style={styles.exportText}>تصدير ومشاركة التقرير</Text></Pressable></View></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { paddingTop: 20, paddingBottom: 32 }, metrics: { flexDirection: "row", gap: 10, marginBottom: 10 }, panel: { backgroundColor: "#FFFFFF", borderRadius: 18, padding: 16, borderWidth: 1, borderColor: "#D8E2E8", marginTop: 12 }, panelTitle: { color: "#16202A", fontSize: 17, fontWeight: "800", textAlign: "right", marginBottom: 8 }, line: { flexDirection: "row-reverse", justifyContent: "space-between", paddingVertical: 11, borderBottomWidth: 1, borderBottomColor: "#EEF2F4" }, label: { color: "#637381", textAlign: "right" }, value: { color: "#0E2A47", fontWeight: "800" }, reportCard: { marginTop: 16, backgroundColor: "#0E2A47", borderRadius: 18, padding: 18, alignItems: "flex-end" }, reportTitle: { color: "#FFFFFF", fontSize: 18, fontWeight: "800", textAlign: "right" }, reportText: { color: "#D3E5E8", textAlign: "right", lineHeight: 21, marginTop: 8 }, export: { marginTop: 16, backgroundColor: "#FFFFFF", paddingVertical: 13, paddingHorizontal: 18, borderRadius: 12, alignSelf: "stretch", alignItems: "center" }, exportText: { color: "#0E2A47", fontWeight: "800" }, pressed: { opacity: 0.72, transform: [{ scale: 0.98 }] } });
