import { useState } from "react";
import { Alert, FlatList, Modal, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import * as Contacts from "expo-contacts";
import { useRouter } from "expo-router";

import { LoadingState } from "@/components/cards/loading-state";
import { ScreenHeader } from "@/components/cards/screen-header";
import { ScreenContainer } from "@/components/screen-container";
import { useCards } from "@/lib/cards/store";
import type { Subscriber } from "@/lib/cards/types";

const EMPTY = { name: "", phone: "", location: "", notes: "" };
export default function SubscribersScreen() {
  const router = useRouter();
  const { subscribers, addSubscriber, isReady } = useCards();
  const [visible, setVisible] = useState(false);
  const [draft, setDraft] = useState(EMPTY);
  const [editing, setEditing] = useState<Subscriber | null>(null);
  if (!isReady) return <LoadingState />;
  const openForm = (subscriber?: Subscriber) => { setEditing(subscriber ?? null); setDraft(subscriber ? { name: subscriber.name, phone: subscriber.phone, location: subscriber.location, notes: subscriber.notes } : EMPTY); setVisible(true); };
  const save = () => { const result = addSubscriber(draft, editing?.id); if (!result.ok) return Alert.alert("تحقق من البيانات", result.message); setVisible(false); Alert.alert("تم الحفظ", result.message); };
  const chooseContact = async () => { if (Platform.OS === "web") return Alert.alert("غير متاح", "اختيار جهات الاتصال متاح على الهاتف فقط."); const permission = await Contacts.requestPermissionsAsync(); if (permission.status !== "granted") return Alert.alert("يلزم الإذن", "اسمح بالوصول إلى جهات الاتصال لاختيار رقم المشترك."); const contact = await Contacts.presentContactPickerAsync(); const phone = contact?.phoneNumbers?.[0]?.number || contact?.phoneNumbers?.[0]?.digits; if (!contact || !phone) return contact ? Alert.alert("لا يوجد رقم", "جهة الاتصال المختارة لا تحتوي على رقم هاتف.") : undefined; setDraft((current) => ({ ...current, name: current.name || contact.name || "", phone })); };
  return <ScreenContainer className="px-4" containerClassName="bg-background"><FlatList data={subscribers} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<><ScreenHeader title="المشتركون" subtitle="أضف بيانات المشتركين وخصص لهم البطاقات" /><View style={styles.editHint}><Text style={styles.editHintIcon}>ⓘ</Text><Text style={styles.editHintText}>اضغط مطولًا على اسم المشترك لتعديل بياناته، واضغط ضغطة عادية لفتح التفاصيل.</Text></View></>} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyText}>لم تتم إضافة مشتركين بعد.</Text></View>} renderItem={({ item }) => <Pressable onPress={() => router.push(`/subscriber/${item.id}` as never)} onLongPress={() => openForm(item)} style={({ pressed }) => [styles.item, pressed && styles.pressed]}><View><Text style={styles.name}>{item.name}</Text><Text style={styles.meta}>{item.phone} {item.location ? `• ${item.location}` : ""}</Text></View><Text style={styles.edit}>عرض</Text></Pressable>} />
    <Pressable onPress={() => openForm()} style={({ pressed }) => [styles.fab, pressed && styles.pressed]}><Text style={styles.fabText}>+ إضافة مشترك</Text></Pressable>
    <Modal visible={visible} animationType="slide" transparent onRequestClose={() => setVisible(false)}><View style={styles.modalBackdrop}><View style={styles.sheet}><Text style={styles.sheetTitle}>{editing ? "تعديل مشترك" : "إضافة مشترك"}</Text><FormField label="اسم المشترك" value={draft.name} onChangeText={(name) => setDraft((item) => ({ ...item, name }))} /><View style={styles.phoneLine}><View style={{ flex: 1 }}><FormField label="رقم الهاتف" value={draft.phone} keyboardType="phone-pad" onChangeText={(phone) => setDraft((item) => ({ ...item, phone }))} /></View><Pressable onPress={chooseContact} style={styles.contactButton}><Text style={styles.contactText}>جهات الاتصال</Text></Pressable></View><FormField label="الموقع" value={draft.location} onChangeText={(location) => setDraft((item) => ({ ...item, location }))} /><FormField label="ملاحظات" value={draft.notes} multiline onChangeText={(notes) => setDraft((item) => ({ ...item, notes }))} /><View style={styles.modalActions}><Pressable onPress={() => setVisible(false)} style={styles.cancel}><Text style={styles.cancelText}>إلغاء</Text></Pressable><Pressable onPress={save} style={styles.save}><Text style={styles.saveText}>حفظ</Text></Pressable></View></View></View></Modal>
  </ScreenContainer>;
}
function FormField({ label, value, onChangeText, keyboardType, multiline }: { label: string; value: string; onChangeText: (value: string) => void; keyboardType?: "phone-pad"; multiline?: boolean }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} keyboardType={keyboardType} multiline={multiline} textAlign="right" placeholder={label} placeholderTextColor="#9AA6AF" style={[styles.input, multiline && styles.multiline]} /></View>; }
const styles = StyleSheet.create({ content: { paddingTop: 20, paddingBottom: 106 }, item: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center", backgroundColor: "#FFFFFF", padding: 16, borderRadius: 16, borderWidth: 1, borderColor: "#D8E2E8", marginBottom: 9 }, name: { textAlign: "right", fontSize: 16, fontWeight: "700", color: "#16202A" }, meta: { textAlign: "right", color: "#637381", marginTop: 4, fontSize: 12 }, edit: { color: "#087E8B", fontWeight: "700" }, editHint: { flexDirection: "row-reverse", alignItems: "center", gap: 8, backgroundColor: "#EAF5F4", borderRadius: 12, padding: 11, marginBottom: 12 }, editHintIcon: { color: "#087E8B", fontSize: 16, fontWeight: "800" }, editHintText: { flex: 1, color: "#087E8B", fontSize: 12, textAlign: "right", lineHeight: 19 }, empty: { backgroundColor: "#FFFFFF", borderRadius: 16, padding: 20 }, emptyText: { color: "#637381", textAlign: "right" }, fab: { position: "absolute", right: 16, left: 16, bottom: 16, backgroundColor: "#0E2A47", padding: 16, borderRadius: 16, alignItems: "center" }, fabText: { color: "#FFFFFF", fontWeight: "800" }, pressed: { opacity: 0.72, transform: [{ scale: 0.98 }] }, modalBackdrop: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(14,42,71,0.34)" }, sheet: { backgroundColor: "#F6F1E9", padding: 20, borderTopLeftRadius: 24, borderTopRightRadius: 24 }, sheetTitle: { textAlign: "right", color: "#16202A", fontSize: 22, fontWeight: "800", marginBottom: 12 }, field: { marginBottom: 12 }, label: { textAlign: "right", color: "#384750", fontSize: 12, marginBottom: 6 }, input: { backgroundColor: "#FFFFFF", color: "#16202A", borderWidth: 1, borderColor: "#D8E2E8", borderRadius: 12, paddingHorizontal: 12, minHeight: 48 }, multiline: { minHeight: 80, textAlignVertical: "top", paddingTop: 12 }, phoneLine: { flexDirection: "row-reverse", gap: 8, alignItems: "flex-end" }, contactButton: { backgroundColor: "#E2F1F2", paddingHorizontal: 10, height: 48, justifyContent: "center", borderRadius: 12, marginBottom: 12 }, contactText: { color: "#087E8B", fontWeight: "700", fontSize: 12 }, modalActions: { flexDirection: "row-reverse", gap: 10, marginTop: 6 }, save: { flex: 1, backgroundColor: "#0E2A47", padding: 14, borderRadius: 12, alignItems: "center" }, saveText: { color: "#FFFFFF", fontWeight: "800" }, cancel: { flex: 1, backgroundColor: "#FFFFFF", padding: 14, borderRadius: 12, alignItems: "center", borderWidth: 1, borderColor: "#D8E2E8" }, cancelText: { color: "#0E2A47", fontWeight: "800" } });
